In [ ]:
import numpy as np

In [2]:
a=[[1, 5], [5, 1]]
b=[[9, 2], [3, 4]]

In [4]:
dot_product_matrix=np.dot(a,b)

In [5]:
dot_product_matrix

array([[24, 22],
       [48, 14]])

In [6]:
outer_product=np.outer(a,b)

In [7]:
outer_product

array([[ 9,  2,  3,  4],
       [45, 10, 15, 20],
       [45, 10, 15, 20],
       [ 9,  2,  3,  4]])

In [8]:
cross_product=np.cross(a,b)

In [9]:
cross_product

array([-43,  17])

In [10]:
cross_product=np.cross(b,a)

In [11]:
cross_product

array([ 43, -17])

In [12]:
det_a=np.linalg.det(a)
det_b=np.linalg.det(b)

In [14]:
det_a,det_b

(-23.999999999999993, 30.000000000000014)

In [15]:
a

[[1, 5], [5, 1]]

In [16]:
b

[[9, 2], [3, 4]]

In [22]:
einsteins=np.einsum("a,b",a,b)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [23]:
a = np.array([1,2,5])
b = np.array([2,1,0])

In [26]:
inner_product=np.inner(a,b)

In [27]:
inner_product

4

In [28]:
a=np.array([[1,2],[3,4]])

In [29]:
eigen_values,eigen_vectors=np.linalg.eig(a)

In [30]:
eigen_values

array([-0.37228132,  5.37228132])

In [31]:
eigen_vectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [32]:
a=[1,2,3]
b=[4,5,6]

In [33]:
knornecker_product=np.kron(a,b)

In [34]:
knornecker_product

array([ 4,  5,  6,  8, 10, 12, 12, 15, 18])

In [35]:
c=[[1,2,3],[4,5,6]]
d=[[4,5,6],[7,8,9]]

In [37]:
print(np.kron(c,d))

[[ 4  5  6  8 10 12 12 15 18]
 [ 7  8  9 14 16 18 21 24 27]
 [16 20 24 20 25 30 24 30 36]
 [28 32 36 35 40 45 42 48 54]]


In [38]:
condition_no=np.linalg.cond(c)

In [39]:
condition_no

12.302245504069207

In [40]:
mat_norm=np.linalg.norm(c)

In [41]:
vect_norm=np.linalg.norm(a)

In [42]:
mat_norm

9.539392014169456

In [43]:
vect_norm

3.7416573867739413

In [46]:
c=[[1,2],[3,4]]
determinant=np.linalg.det(c)

In [47]:
determinant

-2.0000000000000004

In [48]:
inverse=np.linalg.inv(c)

In [49]:
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [50]:
qr=np.linalg.qr(c)

In [51]:
qr

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

In [52]:
condition_no=np.linalg.cond(c)

In [53]:
condition_no

14.933034373659265

In [54]:
diagonal_sum=np.trace(c)

In [55]:
diagonal_sum

5